### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by OMT2011** [ChildrenOfYahweh/Powershell-Token-Grabber#108]
when i open the pumped exe it says the file directory is either corrupted or unreadable
Save me. Discord is exp0s3d

**Comment by KDot227** [comment]
> when i open the pumped exe it says the file directory is either corrupted or unreadable
> 
> Save me. Discord is exp0s3d

Does it work without pumping?

**Comment by OMT2011** [comment]
Lol i have no idea

**Comment by OMT2011** [comment]
Pls just add me on discord

**Comment by KDot227** [comment]
> Pls just add me on discord
> 
> 

Join the server sped.lol

**Comment by OMT2011** [comment]
ok..?

**Comment by KDot227** [comment]
> ok..?
> 
> 

That's my website to the join the server it's literally https://sped.lol

**Comment by OMT2011** [comment]
its a website
what the hell u meaning

**Comment by OMT2011** [comment]
OH SRRY MB

**Comment by OMT2011** [comment]
I joined

**Comment by OMT2011** [comment]
Nice my discord is probably fucking hacked

**Comment by OMT2011** [comment]
welp
thanks for hacking my account :/

**Comment by OMT2011** [comment]
Man

**Comment by OMT2011** [comment]
Why?

**Comment by KDot227** [comment]
Bro what

**Comment by KDot227** [comment]
All u gotta do is press the discord button on my website it can't be that hard

**Comment by OMT2011** [comment]
Its asking me to verify my fucking account now
This is great

**Comment by KDot227** [comment]
Because I set the server verification to the highest so people don't bot it lmao

**Comment by OMT2011** [comment]
Lol can u turn off for like, 2 seconds?

**Comment by OMT2011** [comment]
dont have a good working phone number

**Comment by KDot227** [comment]
No

**Comment by OMT2011** [comment]
F

**Comment by OMT2011** [comment]
Ok Lol

**Comment by OMT2011** [comment]
man what did i do to you
why do i deserve this. Already had my ip fucking stolen 
this week
Why
Why

**Comment by KDot227** [comment]
> man what did i do to you
> 
> why do i deserve this. Already had my ip fucking stolen 
> 
> this week
> 
> Why
> 
> Why

Bro I didn't even do anything use your brain before u accuse me of stuff. I can't get ur discord acc from a link plz grow up and grow a brain.

**Comment by Codepulze** [comment]
💀 dis shit is crazy

**Comment by Beard3dTurtle** [comment]
> man what did i do to you
> why do i deserve this. Already had my ip fucking stolen
> this week
> Why
> Why

Nobody can “steal” ur ip

the worst that can happen is a dos attack which can easily be stopped via ur ISP u dumb nigger

**Comment by hakumaza** [comment]
I have this issue too. Is there a fix?

**Comment by hakumaza** [comment]
The invite expired so I can't go to discord for help.

**Comment by KDot227** [comment]
> The invite expired so I can't go to discord for help.

If I make a server I get banned instantly

**Comment by KDot227** [comment]
> I have this issue too. Is there a fix?

I'll take a look tomorrow. Idk how tf it's overriding the exe code but at this point I'm not even surprised.
