### ISSUE TITLE
Remove it

### ISSUE THREAD

**Issue by delusiony** [ChildrenOfYahweh/Powershell-Token-Grabber#111]
Yo so i was testing it and opened it on my pc the build exe now i wanna remove it can you tell me how i remove the start up and the discord injection please?

**Comment by KDot227** [comment]
read the readme. To remove the injection easiest way is to just delete discord and reinstall unless u wanna manually go to the js file and remove the injection

**Comment by Nitrozena** [comment]
> 

nah i dont mean discord i mean the whole pc startup program like if u turn on pc the info is gonna be send to webhook like passwords and shit but i already removed it

**Comment by KDot227** [comment]
> > 
> 
> 
> 
> nah i dont mean discord i mean the whole pc startup program like if u turn on pc the info is gonna be send to webhook like passwords and shit but i already removed it

"Read the readme"

**Comment by Nitrozena** [comment]
> > > 
> > 
> > 
> > nah i dont mean discord i mean the whole pc startup program like if u turn on pc the info is gonna be send to webhook like passwords and shit but i already removed it
> 
> "Read the readme"

aight thanks for the help
