### ISSUE TITLE
Exodus

### ISSUE THREAD

**Issue by something-0001** [ChildrenOfYahweh/Powershell-Token-Grabber#112]
I am sure you've been made aware or were aware of this to begin with, but, Exodus Sessions are not being stolen.

Is it limited to non-password sessions or is it just failing to grab in general? I'm going by the readme as what the features of this grabber has, so, I just want to know.

**Comment by KDot227** [comment]
> I am sure you've been made aware or were aware of this to begin with, but, Exodus Sessions are not being stolen.
> 
> 
> 
> Is it limited to non-password sessions or is it just failing to grab in general? I'm going by the readme as what the features of this grabber has, so, I just want to know.

I didn't add it @Chainski did but from what I know it doesn't really do anything. U could always make a priv key stealer in js and there are plenty that you can find I've just been very busy lately and haven't really worked on the grabber. If you would like this feature be my guest and add it then make a pr.

**Comment by Chainski** [comment]
> I am sure you've been made aware or were aware of this to begin with, but, Exodus Sessions are not being stolen.
> 
> Is it limited to non-password sessions or is it just failing to grab in general? I'm going by the readme as what the features of this grabber has, so, I just want to know.

Go to my [repository](https://github.com/Chainski/PowerShell-Token-Grabber) and download from there as @KDot227 branch has a few bugs which need investigation.

**Comment by KDot227** [comment]
> > I am sure you've been made aware or were aware of this to begin with, but, Exodus Sessions are not being stolen.
> > Is it limited to non-password sessions or is it just failing to grab in general? I'm going by the readme as what the features of this grabber has, so, I just want to know.
> 
> Go to my [repository](https://github.com/Chainski/PowerShell-Token-Grabber) and download from there as @KDot227 branch has a few bugs which need investigation.

fr I stopped trying

**Comment by something-0001** [comment]
I'll try it out later, but it seems the changes were made into here, so that was pretty neat.

**Comment by KDot227** [comment]
ALL ISSUES FIXED
