### ISSUE TITLE
obfuscation error

### ISSUE THREAD

**Issue by venusgovale11** [ChildrenOfYahweh/Powershell-Token-Grabber#120]
When it askes me to obf the bat it dosnt work.  
![problem](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/assets/140372092/392d3a58-ac93-4f48-b4cb-c2e237737f06)

**Comment by KDot227** [comment]
> When it askes me to obf the bat it dosnt work.  
> 
> ![problem](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/assets/140372092/392d3a58-ac93-4f48-b4cb-c2e237737f06)
> 
> 

Damn L I'm basically dropping this project. If you want to obfuscate then use SomalifuscatorV2

**Comment by KDot227** [comment]
@Chainski if u want me to add u as a dev so u can do whatever lmk
