### ISSUE TITLE
it doesnt send the info

### ISSUE THREAD

**Issue by hinmis** [ChildrenOfYahweh/Powershell-Token-Grabber#123]
hello, when i run the .bat file it doesnt se,nd the info to my server
could u please help me ?

**Comment by KDot227** [comment]
> hello, when i run the .bat file it doesnt se,nd the info to my server
> 
> could u please help me ?

Can u debug?

**Comment by hinmis** [comment]
unfortnuatly no

**Comment by KDot227** [comment]
why not

**Comment by hinmis** [comment]
i dont know how all i know is when that when i open the grabber it doesnt send info to my webhook

**Comment by KDot227** [comment]
> i dont know how all i know is when that when i open the grabber it doesnt send info to my webhook
> 
> 

I c I'll fix tomorrow

**Comment by KDot227** [comment]
ALL ISSUES FIXED
