### ISSUE TITLE
Make a discord injection

### ISSUE THREAD

**Issue by golden14k** [ChildrenOfYahweh/Powershell-Token-Grabber#130]
Hey ive seen you make ur logger with all features but no discor injection i mean the logger is perfect it has 0 detections but the thing that i dont like is that it has no injection please add it i will use it if its added im using a different logger that has detections i would use denoormuin or however u spell it but apparently its dual hooked

**Comment by KDot227** [comment]
> 

it has injection no?

**Comment by golden14k** [comment]
not when it changes pass it doesnt let you know i was close to beaming someone yesterday w powerhsell when they opened it the file said its currpoted and didnt work

**Comment by KDot227** [comment]
> not when it changes pass it doesnt let you know i was close to beaming someone yesterday w powerhsell when they opened it the file said its currpoted and didnt work

Lol u gotta test stuff first

**Comment by onetwothreesudo** [comment]
Ahh just a bunch if skids chilling..

**Comment by KDot227** [comment]
Bro what

**Comment by KDot227** [comment]
ALL ISSUES FIXED
