### ISSUE TITLE
issue in building bat/exe/ps1

### ISSUE THREAD

**Issue by Fntools** [ChildrenOfYahweh/Powershell-Token-Grabber#135]
none of the option working even with the classic manual option of changing the webhook to urs in line 699 , none is working its broken for some reason . i tried older versions still the same problem , the discord link is invalid ( probably termed ). the project seems good especially when its a ps stealer , but its sad cz no one really care abt it , i can debug if you want but i think you need to review or retest

**Comment by KDot227** [comment]
I already know the issues but I'm currently working on a new version that DOESN'T rely on a python payload (it does it all in c# and ports it to powershell)

**Comment by KDot227** [comment]
if you want to make a fix go ahead and make a pr but for now I won't be fixing

**Comment by alnicke** [comment]
@KDot227 i think the reason of error is WE dont have any C# environments. so i can see the red coloured errors. i will download c# environment and try again. and the discord link is expired

**Comment by KDot227** [comment]
ALL ISSUES FIXED
