### ISSUE TITLE
.bat dont show

### ISSUE THREAD

**Issue by Quriqt** [ChildrenOfYahweh/Powershell-Token-Grabber#137]
.bat dont show

**Comment by Quriqt** [comment]
how do i fix it

**Comment by KDot227** [comment]
Fr

**Comment by Quriqt** [comment]
do you know

**Comment by KDot227** [comment]
> do you know

Yeah it's cause I changed Somalifuscator cause of v2 so I gotta rework this project. It's not a hard fix I'll try and get to it tonight

**Comment by KDot227** [comment]
ALL ISSUES FIXED
