### ISSUE TITLE
Has the issue been fixed yet ?

### ISSUE THREAD

**Issue by LGamerzNockz** [ChildrenOfYahweh/Powershell-Token-Grabber#138]
Its been nearly a month and this grabber dosent work . NO HATE

**Comment by KDot227** [comment]
nah u can hate lmao I just keep forgetting to update or add anything new. If I fixed the bat issue and reworked like 2 things it would be wd fud again and should work.

**Comment by LGamerzNockz** [comment]
yeaaa

**Comment by LGamerzNockz** [comment]
webhook dont work :/

:////

**Comment by KDot227** [comment]
ALL ISSUES FIXED
