### ISSUE TITLE
Read below [QUESTION]

### ISSUE THREAD

**Issue by EvilBytecode** [ChildrenOfYahweh/Powershell-Token-Grabber#144]
im currently writing a c2c discord, making it good and opensourced but im lazy to write a get token phase .. is there any way i could use yours payload..  ( i have 1, but only 1 path and im not sure what more are.)

if not just close this issue, thanks 👍.
you will recieve also credits if you want to

**Comment by KDot227** [comment]
> im currently writing a c2c discord, making it good and opensourced but im lazy to write a get token phase .. is there any way i could use yours payload..  ( i have 1, but only 1 path and im not sure what more are.)
> 
> 
> 
> if not just close this issue, thanks 👍.
> 
> you will recieve also credits if you want to

Honestly, mine is pretty bad and I would recommend you just half skid it and remake in a language that isn't python

**Comment by EvilBytecode** [comment]
well if there was an actual good powershell wrapper 4 bots i would make it in powershell but havent found one i might try the discordant... not fan of poshbot, but lets be honest.. people dont even know how to port4ward.. thats why its python and its c2c is a discord, and ill release second ver taht will be tele based

**Comment by EvilBytecode** [comment]
its not that bad, i just will rewrite it a bit, you can check it asw at : https://github.com/orgs/WindKitty/repositories

**Comment by KDot227** [comment]
One of these days I'll end up fixing up my grabber and making a good powershell obf and u can use that too if you want

**Comment by EvilBytecode** [comment]
Well im writing another rat in py ^^ And I Made pow obf ages ago

**Comment by EvilBytecode** [comment]
https://github.com/WindKitty/WindKitty-Rat
