### ISSUE TITLE
error when run builder

### ISSUE THREAD

**Issue by HocCodeViEm** [ChildrenOfYahweh/Powershell-Token-Grabber#145]
![image](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/assets/117921950/ffc35fd2-7aeb-431b-b7ee-20ba5af79605)
![image](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/assets/117921950/f4af74e3-15cf-416c-abd9-77cae4fac714)
![image](https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/assets/117921950/8fb53814-e42e-493b-8347-71ad011086df)
i keep seeing this when building the bat file

**Comment by KDot227** [comment]
> ![image](https://private-user-images.githubusercontent.com/117921950/296321178-ffc35fd2-7aeb-431b-b7ee-20ba5af79605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTEyMzMsIm5iZiI6MTcwOTA5MDkzMywicGF0aCI6Ii8xMTc5MjE5NTAvMjk2MzIxMTc4LWZmYzM1ZmQyLTdhZWItNDMxYi1iN2VlLTIwYmE1YWY3OTYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwMzI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDA3NjVkNWZlOGM3MTZjZTFiMTA3YmU5MzFiMTg2MDljN2NjMzMzYmUxODY4YjU1MGFlMmZhYmI2Njc2MGNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lYSBKdgbx3tf87UNl8lr5V4J4owfrgjs4W-u9QAnqCQ) ![image](https://private-user-images.githubusercontent.com/117921950/296321216-f4af74e3-15cf-416c-abd9-77cae4fac714.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTEyMzMsIm5iZiI6MTcwOTA5MDkzMywicGF0aCI6Ii8xMTc5MjE5NTAvMjk2MzIxMjE2LWY0YWY3NGUzLTE1Y2YtNDE2Yy1hYmQ5LTc3Y2FlNGZhYzcxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwMzI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MjQ1MDAyOGI2ZjRkMDZkYWFlYmRkMGFlMTU4Nzg5OTJjMWU0ZGVlMzliZGViYmU0YWM5MzI1ZWVhN2U0ZDMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.shDz7heGQ1qnbFmtnafev1B71Aj-CV_0di-hOkLjSkI) ![image](https://private-user-images.githubusercontent.com/117921950/296321250-8fb53814-e42e-493b-8347-71ad011086df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwOTEyMzMsIm5iZiI6MTcwOTA5MDkzMywicGF0aCI6Ii8xMTc5MjE5NTAvMjk2MzIxMjUwLThmYjUzODE0LWU0MmUtNDkzYi04MzQ3LTcxYWQwMTEwODZkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOFQwMzI4NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmFiNzA1NWEyZGM4ODA1NjY5ZTIyYjEwZmQ5MTYwYmRlOGQwZTQyYjllZWNmOWQ3OThkM2QzMGFlMzM1MDEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j3Uy0NxSn_2Rz9Xn8Ubxy8a1z6QCDxRJ7WWMhDvMi8w) i keep seeing this when building the bat file

wtf

**Comment by KDot227** [comment]
@HocCodeViEm what is your discord ill help you
