### ISSUE TITLE
Follow-up of a message on VirusTotal

### ISSUE THREAD

**Issue by HeavyTony2** [ChildrenOfYahweh/Powershell-Token-Grabber#147]
There was this message on VirusTotal for this file
https://www.virustotal.com/gui/file/09be0dd0c27c15c4e050aca4d0b593e659fdd8e81d88a38c16b4867d454c8ff6/community

```
Comments
(1)

[thor](https://www.virustotal.com/gui/user/thor/comments)

5 days ago
YARA Signature Match - THOR APT Scanner

RULE: SUSP_PS1_PowerShell_Ipify_Mar23_1
RULE_SET: Livehunt - Suspicious336 Indicators 🏹
RULE_TYPE: THOR APT Scanner&#x27;s rule set only 🔨
RULE_LINK: https://valhalla.nextron-systems.com/info/rule/SUSP_PS1_PowerShell_Ipify_Mar23_1
DESCRIPTION: Detects suspicious PowerShell code that queries api.ipify.org
REFERENCE: https://github.com/KDot227/Powershell-Token-Grabber
RULE_AUTHOR: Florian Roth

🙌 Hey, this seems to be an open-source tool or framework. The author has shared it with the community with the intention to improve overall security. If you are a victim and noticed this tool in a breach, please visit the tool&#x27;s github page (see above) and tell your story by creating an issue on the issues page: https://github.com/KDot227/Powershell-Token-Grabber/issues 💖.

Detection Timestamp: 2024-02-20 14:01
AV Detection Ratio: 🟠 5 / 48

Use these tags to search for similar matches: #ps1 #powershell #ipify #susp_ps1_powershell_ipify_mar23_1 #open_source_tool
More information: https://www.nextron-systems.com/notes-on-virustotal-matches/
```

The concern malware is on this website linked by a fraudulent ad on Facebook. https://solgiveaway.com/?fbclid=IwAR14EvkH4V6kwyZucTRlVaWZRwrV65Uj64t1cCdepSv22dX3c_jbZ1Q3WXU

**Comment by KDot227** [comment]
> There was this message on VirusTotal for this file https://www.virustotal.com/gui/file/09be0dd0c27c15c4e050aca4d0b593e659fdd8e81d88a38c16b4867d454c8ff6/community
> 
> ```
> Comments
> (1)
> 
> [thor](https://www.virustotal.com/gui/user/thor/comments)
> 
> 5 days ago
> YARA Signature Match - THOR APT Scanner
> 
> RULE: SUSP_PS1_PowerShell_Ipify_Mar23_1
> RULE_SET: Livehunt - Suspicious336 Indicators 🏹
> RULE_TYPE: THOR APT Scanner&#x27;s rule set only 🔨
> RULE_LINK: https://valhalla.nextron-systems.com/info/rule/SUSP_PS1_PowerShell_Ipify_Mar23_1
> DESCRIPTION: Detects suspicious PowerShell code that queries api.ipify.org
> REFERENCE: https://github.com/KDot227/Powershell-Token-Grabber
> RULE_AUTHOR: Florian Roth
> 
> 🙌 Hey, this seems to be an open-source tool or framework. The author has shared it with the community with the intention to improve overall security. If you are a victim and noticed this tool in a breach, please visit the tool&#x27;s github page (see above) and tell your story by creating an issue on the issues page: https://github.com/KDot227/Powershell-Token-Grabber/issues 💖.
> 
> Detection Timestamp: 2024-02-20 14:01
> AV Detection Ratio: 🟠 5 / 48
> 
> Use these tags to search for similar matches: #ps1 #powershell #ipify #susp_ps1_powershell_ipify_mar23_1 #open_source_tool
> More information: https://www.nextron-systems.com/notes-on-virustotal-matches/
> ```
> 
> The concern malware is on this website linked by a fraudulent ad on Facebook. https://solgiveaway.com/?fbclid=IwAR14EvkH4V6kwyZucTRlVaWZRwrV65Uj64t1cCdepSv22dX3c_jbZ1Q3WXU

That's cool

**Comment by HeavyTony2** [comment]
What?

**Comment by KDot227** [comment]
> What?

I'm not sure what you want me to do about this.
