### ISSUE TITLE
This is malware. DO NOT DOWNLOAD IT

### ISSUE THREAD

**Issue by Direhash** [ChildrenOfYahweh/Powershell-Token-Grabber#148]
honestly pretty clever but this is just straight up malware LMAO

**Comment by KDot227** [comment]
> honestly pretty clever but this is just straight up malware LMAO

What???

**Comment by KDot227** [comment]
show any malicious code please

**Comment by HeavyTony2** [comment]
> show any malicious code please

That's the result of your compiled main.exe file on VirusTotal
https://www.virustotal.com/gui/file/b54797f916fb6e29066b3bcabff390177cffe574778e07f1812bb1d973a425e1

**Comment by Direhash** [comment]
lol you literally download a .tmp file with main.exe
here you are KDot227 https://tria.ge/240228-dqcxwshh4w/behavioral2
