### ISSUE TITLE
Erroneous credit 

### ISSUE THREAD

**Issue by Purp1eW0lf** [ChildrenOfYahweh/Powershell-Token-Grabber#149]
<img width="648" alt="image" src="https://github.com/ChildrenOfYahweh/Powershell-Token-Grabber/assets/44196051/4ce13c3a-e234-4c65-8696-e28abf4ef419">

I don't think I should be credited for this work. Would you be kind enough to remove any reference or credit of me, for this project

**Comment by KDot227** [comment]
> Purp1eW0lf

Yes. Sorry for the inconvenience.
