### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Eyeif** [ChildrenOfYahweh/Powershell-Token-Grabber#154]
I’m getting this error RAM CHECK Failed.. am I doing anything wrong?

**Comment by KDot227** [comment]
> I’m getting this error RAM CHECK Failed.. am I doing anything wrong? 

That means you have less than 6 mb of ram (ram checking is anti virtual machine.)

**Comment by Eyeif** [comment]
I was testing on rdp.. it worked on my 1st pc but I only got user informations and it doesn’t work on second pc when I ran it

**Comment by Eyeif** [comment]
Are you on discord or telegram? I would like to private chat you

**Comment by KDot227** [comment]
> I was testing on rdp.. it worked on my 1st pc but I only got user informations and it doesn’t work on second pc when I ran it 

Can you try turning on debug mode and reading me the error?

**Comment by KDot227** [comment]
> Are you on discord or telegram? I would like to private chat you 

kdot_227
