### ISSUE TITLE
Source code main.exe

### ISSUE THREAD

**Issue by tinykidpro** [ChildrenOfYahweh/Powershell-Token-Grabber#157]
Can share source code main.exe bro
Thank you

**Comment by KDot227** [comment]
> Can share source code main.exe bro
> 
> Thank you

It's just the main.py file compiled with pyinstaller. There is no obfuscation or anything so you can decompile it or do whatever you want only weird thing I did was build the boot loader for pyinstaller to have it less detected

**Comment by KDot227** [comment]
@tinykidpro u convinced me to make a new backend for the grabber congrats. The new backend is compiled by github and can be seen in the actions tab.
