### ISSUE TITLE
make it so you can disable anti vm

### ISSUE THREAD

**Issue by someguy192** [ChildrenOfYahweh/Powershell-Token-Grabber#165]
i'm trying to run this on a vm, and it's not working cause I am on a vm. I just want to test it, but I can't because I am on a vm.

**Comment by KDot227** [comment]
> i'm trying to run this on a vm, and it's not working cause I am on a vm. I just want to test it, but I can't because I am on a vm.

if you build as ps1 it should work when running on a vm.

**Comment by KDot227** [comment]
I can test if that is true tomorrow. I'm about to go to sleep.

**Comment by someguy192** [comment]
i've built as ps1, and it's not sending to the discord webhook or anything, it's just closing the powershell

**Comment by KDot227** [comment]
> i've built as ps1, and it's not sending to the discord webhook or anything, it's just closing the powershell

that means debug probably isn't turning off all the anti vm checks. One fix would be to increase the ram on your vm and I think that should fix it for now. I will make a better fix by tomorrow night though.

**Comment by KDot227** [comment]
@someguy192 I just updated. Turn on $debug mode and it should skip all the vm checks. Let me know if it works.

**Comment by someguy192** [comment]
Oh sorry. It was something with my VM being stupid and making the execution policy super strict. Also I didn't have debug mode on. Sorry!

**Comment by KDot227** [comment]
> Oh sorry. It was something with my VM being stupid and making the execution policy super strict. Also I didn't have debug mode on. Sorry!

Your good the fix I made should have happened either way you helped point it out (even if it was on accident), If you need any more help just make another issue.

**Comment by KDot227** [comment]
OR IF YOU HAVE ANY SUGGESTIONS (I NEED SUGGESTIONS)

**Comment by someguy192** [comment]
This might be a bug, but please make it so it doesn't spam the output of what it is doing. It makes it very obvious

Also when I did enter to continue, my vm bsoded

**Comment by someguy192** [comment]
Oh i am stupid, that is debug mode.

**Comment by KDot227** [comment]
> This might be a bug, but please make it so it doesn't spam the output of what it is doing. It makes it very obvious
> 
> Also when I did enter to continue, my vm bsoded

Debug mode makes the console appear (turn debug off for no console). the bsoded might be because of the critical process. I will look into it more tomorrow.
