### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vxlkz** [ChildrenOfYahweh/Powershell-Token-Grabber#182]
### Builder.bat
'go' is not recognized as an internal or external command,
operable program or batch file.
"Go is not installed or not in PATH. Either install it or use the prebuilt builder image."
Press any key to continue . . .

**Comment by EvilBytecode** [comment]
please download golang

**Comment by EvilBytecode** [comment]
https://go.dev/doc/install

**Comment by KDot227** [comment]
> ### Builder.bat
> 
> 'go' is not recognized as an internal or external command,
> 
> operable program or batch file.
> 
> "Go is not installed or not in PATH. Either install it or use the prebuilt builder image."
> 
> Press any key to continue . . .

That's for if you want to build the builder otherwise go to the releases and use the version built by GitHub actions.

**Comment by KDot227** [comment]
Stale
